### ISSUE TITLE
[]

### ISSUE THREAD

**Issue by replete** [gdi3d/mute-spotify-ads-mac-osx#14] opened 2021-10-08 14:45 UTC

**Comment by gdi3d** [comment] 2021-10-10 11:12
Thanks for reporting. Do you see this message when you run the script?:

```
Spotify Ads will be silenced while this program is running!. (This works ONLY with the Spotify App, not the web version)
This program was downloaded from https://gdi3d.github.io/mute-spotify-ads-mac-osx/ (check for documentation)

If the program is not working properly please open an issue at: https://github.com/gdi3d/mute-spotify-ads-mac-osx/issues/new

Press control+c to close this program or close the terminal window
```

**Comment by yumulun** [comment] 2021-10-12 00:07
Hi, I am having this issue after I run: sh ~/MuteSpotifyAds/NoAdsSpotify.sh

`osascript: can't open default scripting component.
`
Any insight you might have on what this means?

Thanks for your work!

**Comment by gdi3d** [comment] 2021-10-12 09:23
It's looks like you have a problem with your OSX osascript component. It's not a bug in my script.

Try to google the error: `osascript: can't open default scripting component` to find a fix for it.

I'm closing the ticket since it's not really a bug.

**Closed as completed by gdi3d** 2021-10-12 09:23 UTC

**Comment by gdi3d** [comment] 2021-10-25 08:22
Hey @replete, There are some strange ads that work different and the script is unable to detect them. Unfortunately there's no way to fix it.

In many cases these ads only appears once in a while, but from what I understand this is not your case and is quite often for you.

It's a hard one to fix since I don't see much of them (once per month approx) and debugging gets harder in this case.

Sorry I can't be more helpful.

Closing the ticket now since there's nothing I can do about those ads, and this have been discussed in others tickets as well.
