### ISSUE TITLE
App mutes randomly on BigSur 

### ISSUE THREAD

**Issue by mmt04** [gdi3d/mute-spotify-ads-mac-osx#4] opened 2020-11-19 20:45 UTC
After update to Big Sur, application starts to mute when playing eg. videos on web, sometimes mutes ad with delay or even not at all.

Nice app btw. keep doing the great work!

**Comment by gdi3d** [comment] 2020-11-20 16:27
Hey, I haven't updated to Big Sur yet because of the issues reported by users.

I've encountered the problem that you describe when I was creating the script but I managed to solve it on Catalina. The problem is caused because some web Ad also reports a **track** being played on the event logs. But it seems that the filter that I use to act only on events generated by Spotify is not working properly on Big Sur.

I will patch it as soon I upgrade to Big Sur, but if this is causing a lot of trouble for you I could solve it with your assistance by checking the logs produced by Big Sur in order to create a bugfix.

**Comment by mmt04** [comment] 2020-11-23 13:59
Shure, how can I provide you a log?

**Comment by gdi3d** [comment] 2020-11-29 11:02
Can you run this command on the terminal and paste the result?

`defaults read loginwindow SystemVersionStampAsString`

The command will tell you the Big Sur version number. I think the problem is related to it.

**Comment by mmt04** [comment] 2020-11-30 14:42
11.0.1

**Comment by gdi3d** [comment] 2020-11-30 17:18
Ok, I've release a new version that should take of the problem. If you restart the script it should ask you if you want to update to the new version although it can take a few minutes to detect the new version due to cache.

Let me know if everything works correctly so I can close this ticket.

**Comment by mmt04** [comment] 2020-12-01 16:38
now it works flawlessly, thank you so much! :)

**Comment by gdi3d** [comment] 2020-12-01 16:52
Great to hear that!, thanks for contributing!

**Closed as completed by gdi3d** 2020-12-01 16:52 UTC
